apiVersion: v1
kind: PersistentVolume
metadata:
  name: ignition-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ignition

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ignition-pvc
  namespace: ignition
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
